- name: sync code
  shell: >
    rsync -ru --delete
    --exclude=.git
    --exclude=vendor
    --exclude=web/sites/default/settings.php
    --exclude=web/sites/default/files
    --exclude=web/modules/contrib
    --exclude=web/themes/contrib
    --exclude=web/profiles/contrib
    --exclude=web/core
    /var/source/ /var/web/
  tags: always

- name: composer install
  composer:
    command: install
    working_dir: /var/web
    no_dev: no
  tags:
  - drupal_composer_install
