# ======================================================================
# Clear existing installation
# ======================================================================
- name: remove existing installation
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/web{{ drupal_docroot }}/sites/default/settings.php
  - /var/web{{ drupal_docroot }}/sites/default/files

- name: remove existing database
  shell: mysqladmin drop drupal -f
  register: r
  failed_when: r.rc != 0 and "database doesn't exist" not in r.stderr
  tags: drupal_import_database

- name: make sites directory writable
  file:
    path: /var/web{{ drupal_docroot }}/sites/default
    mode: 0755
    state: directory

- set_fact:
    __drush_install: yes

- name: skip drush install if database is imported
  set_fact:
    __drush_install: no
  tags: drupal_database_import
# ======================================================================
# Install via drush
# ======================================================================
- name: Set config_installer as installation profile.
  set_fact:
    drupal_install_profile: 'config_installer'
  tags: drupal_config_install

- set_fact:
    drupal_install_profile: "{{ drupal_profile }}"
  when: not drupal_install_profile

- set_fact:
    drupal_install_parameters:
      config_installer_sync_configure_form.sync_directory: '../config'
  tags: drupal_config_install

- set_fact:
    drupal_install_params: ''

- set_fact:
    drupal_install_params: >
      {{ drupal_install_params }} {{ item.key }}="{{ item.value }}"
  with_dict: "{{ drupal_install_parameters }}"

- name: install drupal
  shell: >
    drush si
    --account-name={{ drupal_user }}
    --account-pass={{ drupal_pass }}
    --db-url=mysql://root@localhost/drupal
    {{ drupal_install_profile }} -y
    {{ drupal_install_params }}
  args:
    chdir: /var/web{{ drupal_docroot }}/sites/default
  register: r
  when: __drush_install
  failed_when: __install_ignore is undefined and r.rc != 0

# ======================================================================
# Install via dump
# ======================================================================
- name: create settings php
  shell: cp /var/web{{ drupal_docroot }}/sites/default/default.settings.php /var/web{{ drupal_docroot }}/sites/default/settings.php
  tags: drupal_import_database

- name: copy database.settings.php
  copy:
    src: database.settings.php
    dest: /root/database.settings.php
  tags: drupal_import_database

- name: include the database.settings.php
  lineinfile:
    dest: /var/web{{ drupal_docroot }}/sites/default/settings.php
    line: require '/root/database.settings.php';
  tags: drupal_import_database

- name: create database
  shell: mysqladmin create drupal
  tags: drupal_import_database

- name: import database file
  shell: mysql drupal < {{ drupal_database_dump }}
  tags: drupal_import_database

# ======================================================================
# Sync file directories
# ======================================================================
- file:
    state: directory
    path: "{{ item }}"
  with_items:
  - "/var/web{{ drupal_docroot }}/sites/default/files"
  - "{{ drupal_private_files }}"
  - "{{ drupal_temporary_files }}"


- name: sync public files
  shell: rsync -ru --delete /var/data/public/ /var/web{{ drupal_docroot }}/sites/default/files/
  tags: drupal_import_public

- name: sync private files
  shell: rsync -ru --delete /var/data/private/ {{ drupal_private_files }}
  tags: drupal_import_private

- name: fix files directories ownership
  file:
    path: "{{ item }}"
    owner: root
    group: root
    recurse: yes
    state: directory
  with_items:
  - /var/web{{ drupal_docroot }}/sites/default/files
  - "{{ drupal_private_files }}"

