- name: get stat of /var/web
  stat:
    path: /var/web
  register: dir

- name: remove /var/web if its still a link (default in dork.nginx)
  file:
    path: /var/web
    state: absent
  when: dir.stat.islnk is defined and dir.stat.islnk

- name: create docroot as real directory
  file:
    path: /var/web
    state: directory

- include: cli.yml
  tags: drupal_cli

- include: mariadb.yml
  tags: drupal_mariadb

- include: profile.yml
  tags: drupal_profile

- include: root.yml
  tags: drupal_root

- include: composer.yml
  tags: drupal_composer

- name: run drush as root to download dependencies
  shell: drush status
  when: drush.changed
  tags: drupal_cli

- name: create local drush directory
  file:
    path: /root/.drush
    mode: 0755
    state: directory
  tags: drupal_cli

- name: generate drushrc.php
  template:
    src: drushrc.php.j2
    dest: /root/.drush/drushrc.php
  tags: drupal_cli

- name: override nginx vhost
  template:
    src: dork.conf.j2
    dest: /etc/nginx/conf.d/dork.conf

- include: install.yml
  tags: drupal_install

- name: update drupal
  shell: drush updb -y
  ignore_errors: drupal_omg_its_broken
  tags: drupal_update

- name: revert features
  shell: drush fra -y
  ignore_errors: drupal_omg_its_broken
  tags: drupal_features

- name: import configuration
  shell: drush cim --partial -y
  ignore_errors: drupal_omg_its_broken
  tags: drupal_config_import

- name: cache clear
  shell: drush {{ drupal_cache_command }}
  ignore_errors: drupal_omg_its_broken
  tags: drupal_cache

- name: sync build
  shell: >
    rsync -ru --delete
    --exclude=sites/default
    --include=sites/default/default.settings.php
    /var/web/ /var/build/
  tags: always

- include: syslog.yml
  when: drupal_syslog
