- name: copy mariadb configuration
  copy:
    src: drupal-mariadb.cnf
    dest: /etc/my.cnf.d/drupal-mariadb.cnf
  register: mariadb_conf

- name: restart mariadb
  supervisorctl:
    name: mariadb
    state: restarted
  when: mariadb_conf.changed
