- name: get stat of /var/web/sites/default
  stat:
    path: /var/web/sites/default
  register: dir

- name: make sites/default writable
  shell: chmod -R 755 /var/web/sites/default
  tags: core-make
  when: dir.stat.isdir is defined and dir.stat.isdir

- name: build drupal core
  shell: drush make /var/source/drupal-org-core.make -y
  args:
    chdir: /var/web
  tags: core-make

- name: build profile dependencies
  shell: drush make --no-core /var/source/drupal-org.make -y
  args:
    chdir: /var/web
  tags: profile-make

- name: get profile name
  shell: echo ${$(echo *.profile)%.*}
  args:
    chdir: /var/source
    executable: /bin/zsh
  register: profilename_out

- set_fact:
    drupal_profile: "{{ profilename_out.stdout_lines[0] }}"
  when: drupal_profile == 'standard'

- name: link profile directory
  file:
    src: /var/source
    dest: /var/web/profiles/{{ drupal_profile }}
    state: link
