- name: get stat of /var/web{{ drupal_docroot }}/sites/default
  stat:
    path: /var/web{{ drupal_docroot }}/sites/default
  register: dir

- name: make sites/default writable
  shell: chmod -R 755 /var/web{{ drupal_docroot }}/sites/default
  tags: core-make
  when: dir.stat.isdir is defined and dir.stat.isdir

- name: build drupal core
  shell: drush make /var/source/drupal-org-core.make -y
  args:
    chdir: /var/web
  tags: drupal_core_make

- name: build profile dependencies
  shell: drush make --no-core /var/source/drupal-org.make -y
  args:
    chdir: /var/web
  tags: drupal_profile_make

- name: get profile name
  shell: echo ${$(echo *.profile)%.*}
  tags: always
  args:
    chdir: /var/source
    executable: /bin/zsh
  register: profilename_out

- set_fact:
    drupal_profile: "{{ profilename_out.stdout_lines[0] }}"
  tags: always
  when: drupal_profile == 'standard'

- name: remove the profile directory
  file:
    path: /var/web/profiles/{{ drupal_profile }}
    state: absent
  tags: always

- name: recreate the profile directory
  file:
    path: /var/web/profiles/{{ drupal_profile }}
    state: directory
  tags: always

- name: sync the profile directory
  shell: >
    rsync -ru --delete
    --exclude=.git
    /var/source/ /var/web/profiles/{{ drupal_profile }}/
  tags: always
