- name: sync code
  shell: >
    rsync -ru --delete
    --exclude=.git
    --exclude=sites/default/files
    --exclude=sites/default/settings.php
    /var/source{{ drupal_docroot }}/ /var/web/
  tags: always
