- name: install drupal
  shell: /usr/local/composer/vendor/bin/drush si --account-name={{ dork_user }} --account-pass={{ dork_user }} --db-url=mysql://root@localhost/drupal {{ profile }} -y
  sudo_user: "{{ dork_user }}"

- name: update drupal
  shell: /usr/local/composer/vendor/bin/drush updb -y
  sudo_user: "{{ dork_user }}"

- name: revert features
  shell: /usr/local/composer/vendor/bin/drush pm-list --pipe --type=module --status=enabled --no-core | grep features | wc -l
  sudo_user: "{{ dork_user }}"
  register: features
  changed_when: features.stdout_lines[0] == "1"
  notify: really revert features
  tags: features

- name: really revert features
  shell: /usr/local/composer/vendor/bin/drush fra -y
  sudo_user: "{{ dork_user }}"

- name: cache clear
  shell: /usr/local/composer/vendor/bin/drush cc all
  sudo_user: "{{ dork_user }}"

- name: sync build
  sudo_user: "{{ dork_user }}"
  shell: >
    rsync -ru --delete
    --exclude=sites/default
    --include=sites/default/default.settings.php
    /var/web/ /var/build/
  sudo: yes
  sudo_user: root
